server:
  port: 9070
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recipeappDB
      username: JavaUser
      password: root
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}