server:
  port: 9080
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recipeappDB
      username: JavaUser
      password: root
      auto-index-creation: true

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}